version: 2.0
jobs:
  test:
    docker:
      - image: gradle:jdk11
    steps:
      - attach_workspace:
          at: .
      - run:
          name: The First Step
          command: ci/build-app.sh
      - run:
          name: Use test unit
          command: ci/unit-test-app.sh
      - store_test_results:
          path: app/build/test-results

  build:
    docker:
      - image: gradle:jdk11
    steps:
      - attach_workspace:
          at: .
      - run:
          name: The First Step
          command: ci/build-app.sh
      - run:
          name: Use test unit
          command: ci/unit-test-app.sh
      - store_artifacts:
          path: app/build/libs
          destination: build

  clone-down:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: 
            - .

workflows:
  version: 2
  two_job_flows:
    jobs:
      - clone-down
      - build:
          requires:
            - clone-down
      - test:
          requires:
            - clone-down
