version: 2.0
jobs:

  test:
    docker:
      - image: gradle:jdk11
    steps:
      - run:
          name: The First Step
          command: ci/build-app.sh
      - run:
          name: Use test unit
          command: ci/unit-test-app.sh
      - store_test_results:
          path: app/build/test-results

  build:
    docker:
      - image: gradle:jdk11
    steps:
      - run:
          name: The First Step
          command: ci/build-app.sh
      - run:
          name: Use test unit
          command: ci/unit-test-app.sh
      - store_artifacts:
          path: app/build/libs
          destination: build

  clone-down:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout


workflows:
  version: 2
  two_job_flows:
    jobs:
      - clone-down
      - build:
          requires:
            - clone-down
      - test:
          requires:
            - clone-down
