version: 2.0
jobs:
  build:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout
      - run:
          name: The First Step
          command: ci/build-app.sh
      - run:
          name: Use test unit
          command: ci/unit-test-app.sh
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
        path: app/build/
        destination: output
